name: Build

on:
  push:
    branches:
      - qa

jobs:
  build:
    name: Build and analyze product-catalog
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: product-catalog   # 👈 Set working directory

    steps:
      - uses: actions/checkout@v4

      # Install Go dependencies (optional but recommended)
      - name: Download Go dependencies
        run: go mod download

      - uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      # Optional: Fail pipeline if Quality Gate fails
      - uses: SonarSource/sonarqube-quality-gate-action@v1
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
